Improvements
techgaun/active-forks pull request #72
Opened 2022-10-01 17:38 UTC by anzz1

- remove leading/trailing whitespace&slashes https://github.com/techgaun/active-forks/commit/53ac693d5a9602d79a934e5210a425693272348b

- improved bookmarklet https://github.com/techgaun/active-forks/commit/65f0aba0c6087740820026e59ff081f8c730411d
  * check hostname = github.com
  * use url path instead of window title
  * fix alert on error not working
  * stop redirecting original page to a blank page

2022-10-12 18:07 UTC, techgaun requested changes

2022-10-12 18:07 UTC, techgaun commented on js/main.js
> +  repo = repo.replace(/\/+$/,''); // remove trailing slashes
```suggestion
  repo = repo.replace(/^\s+/, ''); // remove leading whitespace
  repo = repo.replace(/\s+$/, ''); // remove trailing whitespace
  repo = repo.replace(/^\/+/, ''); // remove leading slashes
  repo = repo.replace(/\/+$/, ''); // remove trailing slashes
```

2022-11-11 22:27 UTC, techgaun approved these changes

2025-01-15 22:52 UTC, jacob-willden approved these changes

2025-01-15 22:52 UTC, merged